tasks:
  main:
    paused: false
    regen-delay: "30 minutes"

    alert:
      before: "&aRegeneration in 10 seconds..."
      before-delay: "10 seconds"
      after: "&aRegeneration done!"

    min-time: "2 days"
    amount: 10
    efficiency: 90
    radius: 64
    safe-radius: 2

    filters:
      worlds:
        enabled: true
        type: whitelist
        list:
          - world
          - world_nether
          - world_the_end
      materials:
        enabled: true
        type: blacklist
        list:
          - bedrock
          - "minecraft:chest"